#!/usr/bin/env bash
# Put the official engine this run published into `engine-official.nix`, on
# main, through a pull request.
#
#   DOMICILE_ENGINE_TAG=engine-official-s<id> .github/scripts/engine-official-repin.sh
#
# THE PRODUCTION ENGINE IS BUILT AFTER THE MERGE. A pull request that moves the
# fork repins the CHECKED engine (engine-release-repin.sh), because that is
# the build it proved. engine-release.yml builds main nightly as an
# official build -- PGO, ThinLTO, no DCHECKs -- for hours, and this lands what
# it published. The hash is the tarball's and Chromium does not build
# byte-for-byte twice, so this could not have been written any earlier.
#
# MAIN TAKES CHANGES ONLY THROUGH A PULL REQUEST, so this pushes a branch of
# its own, off main's tip, with the one generated file on it, opens a pull
# request and turns on its auto-merge: merged at once it would be refused,
# because its required checks have not run. The branch is this job's alone: it
# is force-pushed, and a pull request a previous run left open is the one set
# to merge.
#
# WITH THE REPOSITORY'S OWN TOKEN, NOT GITHUB_TOKEN. GITHUB_TOKEN may not open
# a pull request here (a 403, run 36785579403), and one it did open would start
# no checks, so it could never merge. DOMICILE_WRITEBACK_TOKEN pushes, opens and
# sets it to merge; packages/domicile-engine/README.md says how it is made.
#
# NOT WHEN MAIN HAS MOVED ON. If another merge moved the fork while this built,
# this engine is of a series main no longer is, and engine-pin.nix would pass
# it over for the checked one anyway. Landing it would be a commit that changes
# nothing, so it is not made; the release of main's own series will be.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

FILE=packages/domicile-engine/engine-official.nix
CHECKED=packages/domicile-engine/engine-release.nix
BRANCH="${DOMICILE_OFFICIAL_PIN_BRANCH:-engine-official-pin}"
REPO="${GITHUB_REPOSITORY:?GITHUB_REPOSITORY names the repository to open the pull request in}"
GITHUB_API="${DOMICILE_GITHUB_API:-https://api.github.com}"
API="$GITHUB_API/repos/$REPO"
: "${DOMICILE_WRITEBACK_TOKEN:?DOMICILE_WRITEBACK_TOKEN is what pushes, opens and merges the pull request}"

identity_of() { sed -n 's/^ *identity = "\([0-9a-f]*\)";.*/\1/p' "$1" | head -1; }

# Generated first, off to the side, so a failure leaves the checkout as it was.
generated="$(mktemp)"
trap 'rm -f "$generated"' EXIT
DOMICILE_ENGINE_PIN_FILE="$generated" ./scripts/update-engine-release.sh

export GIT_AUTHOR_NAME="domicile CI"
export GIT_AUTHOR_EMAIL="ci@domicile.invalid"
export GIT_COMMITTER_NAME="domicile CI"
export GIT_COMMITTER_EMAIL="ci@domicile.invalid"

git fetch -q origin main
git checkout -q -B "$BRANCH" origin/main

built="$(identity_of "$generated")"
main_series="$(identity_of "$CHECKED")"
if [ "$built" != "$main_series" ]; then
  echo "this engine is series ${built:0:12}; main is at series ${main_series:0:12}, so it is not pinned"
  exit 0
fi

cp "$generated" "$FILE"
if [ -z "$(git status --porcelain -- "$FILE")" ]; then
  echo "$FILE already names ${DOMICILE_ENGINE_TAG:-this engine}; nothing to land"
  exit 0
fi

# One file: the checkout is the release job's, and whatever the build left in
# it is not for main.
git add "$FILE"
git commit -q -m "$(cat <<EOF
Point the flake at ${DOMICILE_ENGINE_TAG:-the official engine}

Generated by scripts/update-engine-release.sh and landed by
engine-release.yml, which built and published that official engine (PGO,
ThinLTO, no DCHECKs) from main. engine-pin.nix runs it while
it is of the series the checked pin names.
EOF
)"

# The empty value clears the checkout's header before this one is added.
auth="$(printf 'x-access-token:%s' "$DOMICILE_WRITEBACK_TOKEN" | base64 | tr -d '\n')"
git -c http.https://github.com/.extraheader= \
  -c "http.https://github.com/.extraheader=AUTHORIZATION: basic $auth" \
  push -q -f origin "$BRANCH"

# The body on stdout; anything but a 2xx fails, saying what GitHub answered,
# with 3 for a 422 (what opening a pull request already open answers) and 1
# for the rest.
api() {
  local reply code
  reply="$(mktemp)"
  code="$(curl -sS -o "$reply" -w '%{http_code}' \
    -H "Authorization: Bearer $DOMICILE_WRITEBACK_TOKEN" \
    -H "Accept: application/vnd.github+json" "$@")"
  if [ "${code:0:1}" != 2 ]; then
    echo "GitHub answered $code to $*: $(cat "$reply")" >&2
    rm -f "$reply"
    [ "$code" = 422 ] && return 3
    return 1
  fi
  cat "$reply"
  rm -f "$reply"
}

title="Point the flake at ${DOMICILE_ENGINE_TAG:-the official engine}"
body="Landed by engine-release.yml after publishing the official build of series \`${built:0:12}\`."
request="$(jq -cn --arg title "$title" --arg head "$BRANCH" --arg body "$body" \
  '{title: $title, head: $head, base: "main", body: $body}')"

# A pull request from this branch that a previous run left open is refused
# with a 422; it is then the one to merge, found by its head. Any other refusal
# is the job's failure.
if pr="$(api -X POST -d "$request" "$API/pulls")"; then
  :
else
  status=$?
  [ "$status" = 3 ] || exit "$status"
  pr="$(api "$API/pulls?head=${REPO%%/*}:$BRANCH&state=open" | jq -c '.[0] // empty')"
  [ -n "$pr" ] || { echo "could not open a pull request from $BRANCH" >&2; exit 1; }
fi
number="$(printf '%s' "$pr" | jq -r '.number')"

# GraphQL answers 200 with its errors in the body.
mutation='mutation($id: ID!) { enablePullRequestAutoMerge(input: {pullRequestId: $id, mergeMethod: SQUASH}) { clientMutationId } }'
merge="$(printf '%s' "$pr" | jq -c --arg query "$mutation" '{query: $query, variables: {id: .node_id}}')"
answer="$(api -X POST -d "$merge" "$GITHUB_API/graphql")"
if [ "$(printf '%s' "$answer" | jq '.errors // [] | length')" != 0 ]; then
  echo "could not set #$number to merge: $answer" >&2
  exit 1
fi
echo "#$number merges once its checks pass: $FILE will name ${DOMICILE_ENGINE_TAG:-the official engine}"
