#!/usr/bin/env bash
# Commit the engine this run published to `engine-release.nix` on the branch.
#
#   .github/scripts/engine-release-repin.sh <branch>
#
# `engine.yml` publishes the release from the branch, and this writes it back,
# so the pull request that changes the fork also repins it.
#
# A `pull_request` run checks out `refs/pull/N/merge`. Pushing from there would
# merge main into the branch, so this commits the generated file onto the
# branch tip instead.
#
# If main changed the fork during the run, the identity written is the
# merge's. `scripts/test-the-pinned-engine-is-this-series.sh` then fails and
# the next run fixes it.
set -euo pipefail

BRANCH="${1:-}"
[ -n "$BRANCH" ] || { echo "usage: $(basename "$0") <branch>" >&2; exit 2; }

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

FILE=packages/domicile-engine/engine-release.nix

# Generate before switching branches, so a failure leaves the checkout intact.
./scripts/update-engine-release.sh
generated="$(mktemp)"
cp "$FILE" "$generated"

# Restore the file so `git checkout` cannot refuse to overwrite it. The new
# content is saved in "$generated".
git checkout -q -- "$FILE"

# Set an identity, since the runner's HOME (and git config) is wiped on start.
export GIT_AUTHOR_NAME="domicile CI"
export GIT_AUTHOR_EMAIL="ci@domicile.invalid"
export GIT_COMMITTER_NAME="domicile CI"
export GIT_COMMITTER_EMAIL="ci@domicile.invalid"

git fetch -q origin "$BRANCH"
git checkout -q -B "$BRANCH" "origin/$BRANCH"
cp "$generated" "$FILE"
rm -f "$generated"

# Skip an empty commit, which would re-run every check on the pull request.
if git diff --quiet -- "$FILE"; then
  echo "$FILE already names ${DOMICILE_ENGINE_TAG:-this series}; nothing to push"
  exit 0
fi

# Only this file: the build may have left other changes in the checkout.
git add "$FILE"
git commit -q -m "$(cat <<EOF
Point the flake at ${DOMICILE_ENGINE_TAG:-the engine this branch built}

Generated by scripts/update-engine-release.sh and committed by engine.yml,
which built and published that engine from this branch. A fixed-output
derivation needs the tarball's hash and Chromium does not build byte-for-byte
twice, so this could not be written before the build — which is why it used to
be a second pull request.
EOF
)"

# Runs started by a GITHUB_TOKEN push wait for manual approval, so use
# DOMICILE_WRITEBACK_TOKEN when set. The empty value clears the checkout's
# header before this one is added.
if [ -n "${DOMICILE_WRITEBACK_TOKEN:-}" ]; then
  auth="$(printf 'x-access-token:%s' "$DOMICILE_WRITEBACK_TOKEN" | base64 | tr -d '\n')"
  git -c http.https://github.com/.extraheader= \
    -c "http.https://github.com/.extraheader=AUTHORIZATION: basic $auth" \
    push -q origin "$BRANCH"
else
  git push -q origin "$BRANCH"
fi
echo "pushed $(git rev-parse --short HEAD) to $BRANCH: $FILE now names ${DOMICILE_ENGINE_TAG:-the published engine}"
