#!/usr/bin/env bash
# Put the official engine this run published into `engine-official.nix`, on
# main, through a pull request.
#
#   DOMICILE_ENGINE_TAG=engine-official-s<id> .github/scripts/engine-official-repin.sh
#
# THE PRODUCTION ENGINE IS BUILT AFTER THE MERGE. A pull request that moves the
# fork repins the CHECKED engine (engine-release-repin.sh), because that is
# the build it proved. engine-release.yml then builds the same series as an
# official build -- PGO, ThinLTO, no DCHECKs -- for hours, and this lands what
# it published. The hash is the tarball's and Chromium does not build
# byte-for-byte twice, so this could not have been written any earlier.
#
# MAIN TAKES CHANGES ONLY THROUGH A PULL REQUEST, so this pushes a branch of
# its own, off main's tip, with the one generated file on it, opens a pull
# request and merges it. The branch is this job's alone: it is force-pushed,
# and a pull request a previous run left open is the one merged.
#
# NOT WHEN MAIN HAS MOVED ON. If another merge moved the fork while this built,
# this engine is of a series main no longer is, and engine-pin.nix would pass
# it over for the checked one anyway. Landing it would be a commit that changes
# nothing, so it is not made; the release of main's own series will be.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

FILE=packages/domicile-engine/engine-official.nix
CHECKED=packages/domicile-engine/engine-release.nix
BRANCH="${DOMICILE_OFFICIAL_PIN_BRANCH:-engine-official-pin}"
REPO="${GITHUB_REPOSITORY:?GITHUB_REPOSITORY names the repository to open the pull request in}"
API="${DOMICILE_GITHUB_API:-https://api.github.com}/repos/$REPO"
: "${GH_TOKEN:?GH_TOKEN is what opens and merges the pull request}"

identity_of() { sed -n 's/^ *identity = "\([0-9a-f]*\)";.*/\1/p' "$1" | head -1; }

# Generated first, off to the side, so a failure leaves the checkout as it was.
generated="$(mktemp)"
trap 'rm -f "$generated"' EXIT
DOMICILE_ENGINE_PIN_FILE="$generated" ./scripts/update-engine-release.sh

export GIT_AUTHOR_NAME="domicile CI"
export GIT_AUTHOR_EMAIL="ci@domicile.invalid"
export GIT_COMMITTER_NAME="domicile CI"
export GIT_COMMITTER_EMAIL="ci@domicile.invalid"

git fetch -q origin main
git checkout -q -B "$BRANCH" origin/main

built="$(identity_of "$generated")"
main_series="$(identity_of "$CHECKED")"
if [ "$built" != "$main_series" ]; then
  echo "this engine is series ${built:0:12}; main is at series ${main_series:0:12}, so it is not pinned"
  exit 0
fi

cp "$generated" "$FILE"
if [ -z "$(git status --porcelain -- "$FILE")" ]; then
  echo "$FILE already names ${DOMICILE_ENGINE_TAG:-this engine}; nothing to land"
  exit 0
fi

# One file: the checkout is the release job's, and whatever the build left in
# it is not for main.
git add "$FILE"
git commit -q -m "$(cat <<EOF
Point the flake at ${DOMICILE_ENGINE_TAG:-the official engine}

Generated by scripts/update-engine-release.sh and landed by
engine-release.yml, which built and published that official engine (PGO,
ThinLTO, no DCHECKs) from main after the merge. engine-pin.nix runs it while
it is of the series the checked pin names.
EOF
)"

# The writeback token when there is one, as engine-release-repin.sh does.
if [ -n "${DOMICILE_WRITEBACK_TOKEN:-}" ]; then
  auth="$(printf 'x-access-token:%s' "$DOMICILE_WRITEBACK_TOKEN" | base64 | tr -d '\n')"
  git -c http.https://github.com/.extraheader= \
    -c "http.https://github.com/.extraheader=AUTHORIZATION: basic $auth" \
    push -q -f origin "$BRANCH"
else
  git push -q -f origin "$BRANCH"
fi

api() {
  curl -fsS -H "Authorization: Bearer $GH_TOKEN" \
    -H "Accept: application/vnd.github+json" "$@"
}

title="Point the flake at ${DOMICILE_ENGINE_TAG:-the official engine}"
body="Landed by engine-release.yml after publishing the official build of series \`${built:0:12}\`."
request="$(jq -cn --arg title "$title" --arg head "$BRANCH" --arg body "$body" \
  '{title: $title, head: $head, base: "main", body: $body}')"

# A pull request from this branch that a previous run left open is refused
# with a 422; it is then the one to merge, found by its head.
if created="$(api -X POST -d "$request" "$API/pulls")"; then
  number="$(printf '%s' "$created" | jq -r '.number')"
else
  number="$(api "$API/pulls?head=${REPO%%/*}:$BRANCH&state=open" | jq -r '.[0].number // empty')"
  [ -n "$number" ] || { echo "could not open a pull request from $BRANCH" >&2; exit 1; }
fi

api -X PUT -d '{"merge_method": "squash"}' "$API/pulls/$number/merge" >/dev/null
echo "merged #$number: $FILE now names ${DOMICILE_ENGINE_TAG:-the official engine}"
