#!/usr/bin/env bash
# Put the engine the merge queue published into `engine-release.nix`, on main.
#
#   .github/scripts/engine-release-repin.sh <branch>
#
# THIS IS THE SECOND PULL REQUEST, REPLACED BY A COMMIT. An engine change used
# to be two: one that moved the fork, and one that moved `engine-release.nix`
# onto the tarball a manually dispatched release produced. That second one ran
# this repository's most expensive job twice more, and — being manual — is the
# one that got skipped, so changes needing a release shipped without one.
#
# `engine.yml` publishes the release from the merge queue now, under a tag
# naming the SERIES rather than the commit, and `engine-repin.yml` runs this on
# the push to main that follows. It used to push onto the pull request's
# branch; a merge group's branch is deleted once it merges, so there is no
# branch left to push to but main.
#
# MAIN'S TIP, NOT THE CHECKOUT, AND THAT IS MOST OF THIS SCRIPT. The run is
# checked out at the commit whose push started it, and the queue can merge the
# next change while this is still hashing a tarball. A commit on the checkout
# would be a push main refuses, or, forced, one that throws that merge away. So
# the tip is fetched and the generated file is put on it, alone.
#
# If that next merge moved the fork again, the identity written here is this
# series rather than the tip's. `scripts/test-the-pinned-engine-is-this-series.sh`
# goes red, the next merge's own run of this fixes it, and that is the cheap
# direction to be wrong in — the expensive one is a main that looks repinned
# and is not.
set -euo pipefail

BRANCH="${1:-}"
[ -n "$BRANCH" ] || { echo "usage: $(basename "$0") <branch>" >&2; exit 2; }

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

FILE=packages/domicile-engine/engine-release.nix

# Generated first, while the checkout is still the pushed commit — the generator
# reads nothing from the working tree but the output path, and running it
# before the branch is checked out keeps a failure from leaving a half-switched
# checkout behind.
./scripts/update-engine-release.sh
generated="$(mktemp)"
cp "$FILE" "$generated"

# Its own identity, so a `git am` or a `commit` here cannot fail on a runner
# whose HOME is deleted on every start. See engine.yml, where this failed the
# apply step in zero seconds and looked like the patches not applying.
export GIT_AUTHOR_NAME="domicile CI"
export GIT_AUTHOR_EMAIL="ci@domicile.invalid"
export GIT_COMMITTER_NAME="domicile CI"
export GIT_COMMITTER_EMAIL="ci@domicile.invalid"

git fetch -q origin "$BRANCH"
git checkout -q -B "$BRANCH" "origin/$BRANCH"
cp "$generated" "$FILE"
rm -f "$generated"

# NOTHING TO SAY IS NOT A COMMIT. A re-run of a green job reaches here with the
# file already holding what the generator produces, and an empty commit pushed
# to main on every re-run would re-trigger every check there for no change.
if git diff --quiet -- "$FILE"; then
  echo "$FILE already names ${DOMICILE_ENGINE_TAG:-this series}; nothing to push"
  exit 0
fi

# One file. Anything else in this commit is CI editing main, and the checkout
# it is standing in is a working tree a job has been using — so `-A` here would
# sweep up whatever the job left lying around.
git add "$FILE"
git commit -q -m "$(cat <<EOF
Point the flake at ${DOMICILE_ENGINE_TAG:-the engine the merge queue built}

Generated by scripts/update-engine-release.sh and committed by
engine-repin.yml, after the merge queue's engine build published that engine.
A fixed-output derivation needs the tarball's hash and Chromium does not build
byte-for-byte twice, so this could not be written before the build — which is
why it used to be a second pull request.
EOF
)"

# A push with the workflow's GITHUB_TOKEN starts no workflows at all, so main's
# new tip would show no checks. A token of the repository's own, when there is
# one, starts them. Either identity has to be allowed past the ruleset's merge
# queue to push to main at all; see engine-repin.yml.
# The empty value clears the checkout's header before this one is added.
if [ -n "${DOMICILE_WRITEBACK_TOKEN:-}" ]; then
  auth="$(printf 'x-access-token:%s' "$DOMICILE_WRITEBACK_TOKEN" | base64 | tr -d '\n')"
  git -c http.https://github.com/.extraheader= \
    -c "http.https://github.com/.extraheader=AUTHORIZATION: basic $auth" \
    push -q origin "$BRANCH"
else
  git push -q origin "$BRANCH"
fi
echo "pushed $(git rev-parse --short HEAD) to $BRANCH: $FILE now names ${DOMICILE_ENGINE_TAG:-the published engine}"
