//! Locates the file index: `$XDG_CACHE_HOME/domicile/file-index`, else
//! `~/.cache/domicile/file-index`.
//!
//! It is a cache, not state, because it can be regenerated by a walk. The
//! environment is passed in so the lookup is testable.

use std::path::PathBuf;

/// This program's directory under the cache home.
const DIRECTORY: &str = "domicile";

/// The index file name.
const FILE: &str = "file-index";

/// The index path, or `None` if neither `XDG_CACHE_HOME` nor `HOME` is set
/// to an absolute path.
pub fn index_file(env: &dyn Fn(&str) -> Option<String>) -> Option<PathBuf> {
    cache_home(env).map(|home| home.join(DIRECTORY).join(FILE))
}

/// The cache home: `XDG_CACHE_HOME` if absolute, else `~/.cache`.
///
/// The spec says to ignore a relative value, which would depend on the
/// working directory.
fn cache_home(env: &dyn Fn(&str) -> Option<String>) -> Option<PathBuf> {
    let absolute = |value: String| {
        let path = PathBuf::from(value);
        path.is_absolute().then_some(path)
    };
    env("XDG_CACHE_HOME").and_then(absolute).or_else(|| {
        env("HOME")
            .and_then(absolute)
            .map(|home| home.join(".cache"))
    })
}
