# Which published engine `nix build .#engine` produces.
#
# GENERATED by scripts/update-engine-release.sh. Edit that, not this.
#
# A fixed-output derivation needs a hash, and a hash pins a build — which is
# the point rather than a cost. Without this file the same flake revision would
# fetch a different engine on different days, and a bug reported against one
# could not be reproduced. With it, a flake revision names exactly one engine,
# and moving to a new one is a commit somebody can look at.
#
# The url is the release tagged with the engine's own SERIES, not
# `engine-nightly`: the nightly is deleted and recreated on every release
# run, and a pin to it stops resolving as soon as the next build lands.
#
# `identity` is that series — the pin, `patches/` and `src/` hashed by
# content, the same value `engine-series-stamp.sh` uses to decide whether the
# shared checkout needs rebuilding. It is here so that
# `scripts/test-the-pinned-engine-is-this-series.sh` can ask, without
# downloading anything, whether the engine this repository pins is the engine
# this repository describes. Two commits that do not move the fork have the
# same identity and so need no repin between them.
{
  identity = "42e82b6b6e8d3a3340bc24f9e82c55536cdcec667cc69012fd6df32dbe3a0ad5";
  commit = "86fcc018d50584dc6e4cc3342541a5ff4971d6df";
  url = "https://github.com/cprussin/domicile/releases/download/engine-s42e82b6b6e8d/domicile-engine-s42e82b6b6e8d-linux-x64.tar.zst";
  hash = "sha256-Pyp+2sxbQ/mP2Y1mQtyo+pnIrZWR2hIKy/Pdvp1oELI=";
}
