# Which published engine `nix build .#engine` produces.
#
# GENERATED by scripts/update-engine-release.sh. Edit that, not this.
#
# A fixed-output derivation needs a hash, and a hash pins a build — which is
# the point rather than a cost. `engine-nightly` is a rolling tag: without
# this file the same flake revision would fetch a different engine on different
# days, and a bug reported against one could not be reproduced. With it, a
# flake revision names exactly one engine, and moving to a new one is a commit
# somebody can look at.
{
  commit = "32c2132e7b93598f8404a6dd736086cb67c83464";
  url = "https://github.com/cprussin/domicile/releases/download/engine-nightly/domicile-engine-32c2132-linux-x64.tar.zst";
  hash = "sha256-xAb/pX+LLkWWrVnexbIYr+88pBZmN7XP6pYsxaD0eT0=";
}
