# One published engine `nix build .#engine` can fetch; engine-pin.nix says
# which of the two pins it does.
#
# GENERATED by scripts/update-engine-release.sh. Edit that, not this.
#
# A fixed-output derivation needs a hash, and a hash pins a build — which is
# the point rather than a cost. Without this file the same flake revision would
# fetch a different engine on different days, and a bug reported against one
# could not be reproduced. With it, a flake revision names exactly one engine,
# and moving to a new one is a commit somebody can look at.
#
# The url is the release tagged with the engine's own SERIES, not
# `engine-nightly`: the nightly is deleted and recreated on every release
# run, and a pin to it stops resolving as soon as the next build lands.
#
# `identity` is that series — the pin, `patches/` and `src/` hashed by
# content, the same value `engine-series-stamp.sh` uses to decide whether the
# shared checkout needs rebuilding. It is here so that
# `scripts/test-the-pinned-engine-is-this-series.sh` can ask, without
# downloading anything, whether the engine this repository pins is the engine
# this repository describes. Two commits that do not move the fork have the
# same identity and so need no repin between them.
{
  identity = "e0dc7ef25d969bd25ed446b29b4044a8d4a97e75121635a53973b3b5e4a30010";
  commit = "3b2a4ed262accd57b5b77a7b58762f417f5babe7";
  url = "https://github.com/cprussin/domicile/releases/download/engine-official-se0dc7ef25d96/domicile-engine-se0dc7ef25d96-linux-x64.tar.zst";
  hash = "sha256-6oh4iuLafNcYMEsmepf6nHswITcPoljl+9hmf9AFsk4=";
}
