# Which published engine `nix build .#engine` produces.
#
# GENERATED by scripts/update-engine-release.sh. Edit that, not this.
#
# A fixed-output derivation needs a hash, and a hash pins a build — which is
# the point rather than a cost. Without this file the same flake revision would
# fetch a different engine on different days, and a bug reported against one
# could not be reproduced. With it, a flake revision names exactly one engine,
# and moving to a new one is a commit somebody can look at.
#
# The url is the release tagged with the engine's own SERIES, not
# `engine-nightly`: the nightly is deleted and recreated on every release
# run, and a pin to it stops resolving as soon as the next build lands.
#
# `identity` is that series — the pin, `patches/` and `src/` hashed by
# content, the same value `engine-series-stamp.sh` uses to decide whether the
# shared checkout needs rebuilding. It is here so that
# `scripts/test-the-pinned-engine-is-this-series.sh` can ask, without
# downloading anything, whether the engine this repository pins is the engine
# this repository describes. Two commits that do not move the fork have the
# same identity and so need no repin between them.
{
  identity = "f4c8bb30f70144caacbb92384706b796d8bfa1ce20bd706a50676477aaa27184";
  commit = "d5dcb6fa1967a9cca610e357df8c33c1145e2795";
  url = "https://github.com/cprussin/domicile/releases/download/engine-sf4c8bb30f701/domicile-engine-sf4c8bb30f701-linux-x64.tar.zst";
  hash = "sha256-8B3BbNIz8qndjDQZR73AXDprffbmYs9Rhf5SdEKth0A=";
}
