#!/usr/bin/env bash
# Is the engine this checkout PINS the engine this checkout DESCRIBES?
#
# `packages/domicile-engine/` is the fork: a Chromium revision, a patch series
# over it, and the files the series copies in. `engine-release.nix` is a url
# and a hash naming one published tarball. Nothing tied the two together, so a
# change to the fork that never got a release left the repository describing
# one engine and shipping another — and every check stayed green, because
# every check looked at one half.
#
# THAT IS #411, AND IT IS WHY THIS IS CHEAP RATHER THAN CLEVER.
# `pinned-engine.yml` catches the case where the mismatch happens to break the
# C ABI: it runs the pixel guard against the pinned tarball, so a compositor
# that reads a field the old engine does not have aborts there. What it cannot
# catch is a mismatch that does not break the ABI — a rendering fix, a DRM
# patch, a shortcut that stops working — because the guard passes and the
# engine is still the wrong one. This asks the question directly instead: the
# release records which series it was built from, and the series is right here.
#
# BOTH SIDES ARE LOCAL, so this is a string comparison and runs on
# `ubuntu-latest` in seconds. Nothing is downloaded and no Chromium tree is
# touched — which is the whole point, because the thing this guards is the
# most expensive job in the repository and a guard that had to queue behind it
# would not be worth having.
#
# WHAT RED MEANS ON A PULL REQUEST IS "NOT YET", NOT "WRONG". A change that
# moves the fork is red here until the engine job publishes the engine and
# writes `engine-release.nix` back to the branch — which it does, in the same
# pull request, so a merge is sufficient and there is no second one to forget.
# Red that stays red past that is the real signal: the release never happened.
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STAMP="$ROOT/.github/scripts/engine-series-stamp.sh"
RELEASE="$ROOT/packages/domicile-engine/engine-release.nix"

[ -x "$STAMP" ] || { echo "no $STAMP" >&2; exit 1; }
[ -f "$RELEASE" ] || { echo "no $RELEASE" >&2; exit 1; }

# The series in hand: the pin, every patch and every laid-down file, hashed by
# content. Read out of the script that already computes it for the shared
# checkout rather than computed again here — the two have to mean the same
# thing, and a second implementation is a second thing that can drift.
want="$("$STAMP" identity)"

# The series the pinned release was built from, as `update-engine-release.sh`
# wrote it. Parsed rather than evaluated: `nix` is not on every machine that
# runs `check.sh`, and this file is generated by one script and read by that
# script's own format.
got="$(sed -n 's/^[[:space:]]*identity[[:space:]]*=[[:space:]]*"\([0-9a-f]*\)".*/\1/p' "$RELEASE" | head -1)"

if [ -z "$got" ]; then
  # A file with no identity in it predates this check, and the fix is not a
  # judgment call — it is one command. Said rather than inferred, because the
  # alternative reading ("the engine is wrong") sends the reader at the fork.
  {
    echo "  FAIL  $RELEASE records no series identity"
    echo "        It is generated, and the generator writes that field now:"
    echo "          ./scripts/update-engine-release.sh"
  } >&2
  exit 1
fi

if [ "$got" != "$want" ]; then
  {
    echo "  FAIL  the pinned engine was built from a different series than this checkout carries"
    echo "        this checkout: $want"
    echo "        the pin:       $got"
    echo
    echo "        Either packages/domicile-engine changed without a release, or"
    echo "        engine-release.nix was not moved onto the one that was"
    echo "        published. On a pull request that moves the fork this is"
    echo "        expected until the engine job on crux publishes the engine"
    echo "        and writes this file back to the branch; that push is what"
    echo "        turns it green, and it is why the repin is not a second pull"
    echo "        request."
    echo
    echo "        By hand, once a release for this series exists:"
    echo "          ./scripts/update-engine-release.sh"
  } >&2
  exit 1
fi

echo "  ok    the pinned engine is this checkout's series ($want)"
