#!/usr/bin/env bash
# Whether a published engine stays fetchable after the next one is published.
#
# `engine-nightly` is DELETED AND RECREATED on every release run, so the asset
# a checkout is pinned to stops existing the moment anybody cuts a new build:
# `nix run` on main answers `cannot download ... from any mirror` and every
# open pull request goes red on `packages` for a reason none of them caused.
# That happened twice in one afternoon. The fix is a second release per build,
# tagged with the commit and never deleted, and this is what says it is still
# there.
#
# Against a fake GitHub, because the real one cannot be asked "and what would
# you have done" — and a test that publishes to check publishing has published.
# The fake records every request and answers as the API does, which is enough:
# what is under test is which releases the script creates, which it leaves
# alone, and where the assets go.
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PUBLISH="$ROOT/.github/scripts/engine-release-publish.sh"
[ -f "$PUBLISH" ] || { echo "no $PUBLISH" >&2; exit 1; }

# `SKIP:` on stdout and nothing else: that prefix is what `check.sh` reads the
# reason out of (`sed -n 's/^ *SKIP: *//p'`), and a reason printed any other way
# is one the runner never shows -- under `DOMICILE_CHECK_STRICT=1` it becomes a
# `FAILED ()` with nothing in the parentheses.
command -v jq >/dev/null 2>&1 || {
  echo "SKIP: no jq, which both the publisher and the fake GitHub here parse with"
  exit 77
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

BIN="$WORK/bin"
mkdir -p "$BIN"

# The stage the packaging step leaves behind: a tarball and the digest beside
# it. Contents are never read by the publisher, only uploaded.
STAGE="$WORK/stage"
TARBALL="domicile-engine-deadbee-linux-x64.tar.zst"
mkdir -p "$STAGE"
echo "not really a tarball" > "$STAGE/$TARBALL"
echo "not really a digest" > "$STAGE/$TARBALL.sha256"

cat > "$BIN/curl" <<'FAKE'
#!/usr/bin/env bash
# GitHub, as far as the publisher can tell. Every call is appended to
# `$STATE/calls` as `<METHOD> <url>`; a release exists iff `$STATE/rel-<tag>`
# does, and `-f` is honoured by exiting 22 when it does not.
set -u
state="$FAKE_STATE"
method=GET; url=""; stdin_body=0; upload=""
prev=""
for arg in "$@"; do
  [ "$prev" = "-X" ] && method="$arg"
  case "$arg" in
    http*) url="$arg" ;;
    @-) stdin_body=1 ;;
    @*) upload="${arg#@}" ;;
  esac
  prev="$arg"
done
echo "$method $url" >> "$state/calls"

if [ -n "$upload" ]; then
  # `.../releases/<id>/assets?name=<file>`
  id="${url#*/releases/}"; id="${id%%/assets*}"
  echo "$id ${url##*name=}" >> "$state/assets"
  exit 0
fi

case "$method" in
  GET)
    tag="${url##*/}"
    [ -f "$state/rel-$tag" ] || exit 22
    cat "$state/rel-$tag"
    ;;
  POST)
    body=""; [ "$stdin_body" = 1 ] && body="$(cat)"
    tag="$(printf '%s' "$body" | jq -r .tag_name)"
    printf '%s' "$body" > "$state/created-$tag.json"
    jq -n --arg tag "$tag" \
      '{id: ("id-" + $tag), html_url: ("https://example.invalid/" + $tag)}' \
      > "$state/rel-$tag"
    cat "$state/rel-$tag"
    ;;
  DELETE)
    # By id, which the fake made from the tag, so the tag is recoverable.
    id="${url##*/}"
    echo "${id#id-}" >> "$state/deleted"
    rm -f "$state/rel-${id#id-}"
    ;;
esac
FAKE
chmod +x "$BIN/curl"

# What the tarball is named after, and what the immutable tag must therefore
# be: the two are generated by different scripts in the same checkout, and a
# test that computed it a third way would not notice them drifting apart.
REV="$(cd "$ROOT" && git rev-parse --short HEAD)"
PINNABLE="engine-$REV"

FAILED=0
fail() { echo "  FAIL: $*" >&2; FAILED=1; }

# One run of the publisher against a fresh fake. `$1` is the state directory to
# use, which a caller can pre-seed with releases that already exist.
publish() {
  local state="$1"; shift
  mkdir -p "$state"
  : > "$state/calls"
  : > "$state/assets"
  : > "$state/deleted"
  # `env`, not a bare prefix: an assignment that arrives by expansion is a
  # command name, not an assignment, so `"$@"` in front of `bash` ran
  # `GITHUB_REF_TYPE=tag: command not found` and the tag case tested nothing.
  ( cd "$ROOT" && env PATH="$BIN:$PATH" FAKE_STATE="$state" \
      GITHUB_TOKEN=fake GITHUB_REPOSITORY=cprussin/domicile \
      GITHUB_SHA=0123456789abcdef0123456789abcdef01234567 \
      "$@" bash "$PUBLISH" "$STAGE" "$TARBALL" ) > "$state/out" 2>&1
}

echo "a nightly publishes a release that is never replaced"
state="$WORK/nightly"
publish "$state" || { cat "$state/out" >&2; fail "publisher exited nonzero"; }

[ -f "$state/created-engine-nightly.json" ] ||
  fail "no engine-nightly was created"
[ -f "$state/created-$PINNABLE.json" ] ||
  fail "no $PINNABLE was created; a pin would point at the rolling tag"

# Both assets on BOTH releases. Uploading only to the nightly would make the
# immutable release a tag with nothing behind it, which 404s exactly as before.
for release in engine-nightly "$PINNABLE"; do
  count="$(grep -c "^id-$release " "$state/assets" || true)"
  [ "$count" = "2" ] ||
    fail "$release got $count assets, wanted the tarball and its digest"
done

# So that nothing downstream has to guess the tag from the commit: the rolling
# release says which immutable one holds the same build.
body="$(jq -r .body "$state/created-engine-nightly.json")"
case "$body" in
  (*"immutable release: \`$PINNABLE\`"*) ;;
  (*) fail "engine-nightly's body does not name $PINNABLE" ;;
esac

echo "publishing again leaves an already published commit alone"
# The whole point of the second release: something may already be pinned to it.
# A second run for the same commit -- a re-dispatch, a retry -- must not delete
# and recreate it, because that is the rolling tag's bug with a longer name.
again="$WORK/again"
mkdir -p "$again"
cp "$state/rel-engine-nightly" "$state/rel-$PINNABLE" "$again/" 2>/dev/null
publish "$again" || { cat "$again/out" >&2; fail "publisher exited nonzero"; }
grep -qx "$PINNABLE" "$again/deleted" &&
  fail "$PINNABLE was deleted; a pin to it would have broken"
[ -f "$again/created-$PINNABLE.json" ] &&
  fail "$PINNABLE was recreated rather than left alone"
grep -qx "engine-nightly" "$again/deleted" ||
  fail "engine-nightly was not replaced; it must always mean the newest build"

echo "a pushed tag is published once, under the name that was pushed"
# An `engine-v*` tag is already immutable. A second copy under another name
# would be two names for one build with nothing to choose between them.
tagged="$WORK/tagged"
publish "$tagged" GITHUB_REF_TYPE=tag GITHUB_REF_NAME=engine-v1.2.3 ||
  { cat "$tagged/out" >&2; fail "publisher exited nonzero"; }
[ -f "$tagged/created-engine-v1.2.3.json" ] ||
  fail "the pushed tag was not published"
[ -f "$tagged/created-$PINNABLE.json" ] &&
  fail "a pushed tag was copied to $PINNABLE"
case "$(jq -r .body "$tagged/created-engine-v1.2.3.json")" in
  (*"immutable release"*) fail "a pushed tag points at an immutable release that is itself" ;;
esac
# And its own tag is a fact about the history: deleting it would rewrite what
# somebody else is pointing at.
grep -q . "$tagged/deleted" 2>/dev/null &&
  fail "a pushed tag's release was deleted: $(cat "$tagged/deleted")"

[ "$FAILED" = "0" ] || exit 1
echo "engine-release-publish: a published engine stays fetchable"
