#!/usr/bin/env bash
# Checks that each `:<name>_blink` mojom variant the fork depends on is
# generated by its target.
#
# The mojom template emits the Blink variant only for a target that sets
# `generate_blink = true`. Without it, `gn gen` fails with "Unresolved
# dependencies" before anything compiles, and no check that reads C++ or
# patches notices.
#
# Requires the opt-in for targets the fork owns. Upstream targets are only
# reported.
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SERIES="$ROOT/packages/domicile-engine"
SRC="$SERIES/src"

[ -d "$SRC" ] || { echo "no $SRC" >&2; exit 1; }
[ -d "$SERIES/patches" ] || { echo "no $SERIES/patches" >&2; exit 1; }

FAILED=0
ok() { printf '  ok    %s\n' "$1"; }
fail() {
  printf '  FAIL  %s\n    %s\n' "$1" "$2"
  FAILED=$((FAILED + 1))
}

# Every `//path:name_blink` the fork names, in `BUILD.gn` files under `src/`
# and in lines added by patches.
blink_refs() {
  {
    grep -rhoE '//[A-Za-z0-9_/.-]+:[A-Za-z0-9_-]+_blink' "$SRC" --include=BUILD.gn --include='*.gni' 2>/dev/null
    grep -rhoE '^\+.*//[A-Za-z0-9_/.-]+:[A-Za-z0-9_-]+_blink' "$SERIES"/patches/*.patch 2>/dev/null |
      grep -oE '//[A-Za-z0-9_/.-]+:[A-Za-z0-9_-]+_blink'
  } | sort -u
}

# Whether a top-level `mojom("x")` or `mojom_component("x")` in this file sets
# `generate_blink = true`. Dependencies use both forms.
declares_generate_blink() {
  awk -v n="$2" '
    $0 ~ "^mojom(_component)?\\(\"" n "\"\\)" { inside = 1; next }
    inside && /^\}/ { inside = 0 }
    inside && /generate_blink[[:space:]]*=[[:space:]]*true/ { found = 1 }
    END { exit(found ? 0 : 1) }
  ' "$1"
}

REFS="$(blink_refs)"

# An empty list would pass vacuously, which is what a moved directory or
# reformatted dependency block produces.
if [ -z "$REFS" ]; then
  echo "no :<name>_blink references found in $SRC or the patch series" >&2
  echo "either the fork stopped using Blink bindings, or this script has stopped reading them" >&2
  exit 1
fi

echo "the fork names $(printf '%s\n' "$REFS" | wc -l) blink variant(s):"

for ref in $REFS; do
  path="${ref%%:*}"
  path="${path#//}"
  target="${ref##*:}"
  base="${target%_blink}"
  build_gn="$SRC/$path/BUILD.gn"

  if [ ! -f "$build_gn" ]; then
    # An upstream target. There is no Chromium checkout to read, so report it
    # instead of claiming a pass.
    printf '  --    %s is upstream'"'"'s (no %s in the series)\n' "$ref" "src/$path/BUILD.gn"
    continue
  fi

  if declares_generate_blink "$build_gn" "$base"; then
    ok "$ref is generated: $path/BUILD.gn opts in"
  else
    fail "$ref is generated: $path/BUILD.gn opts in" \
      "mojom(\"$base\") there does not set generate_blink = true, so the template emits no blink variant and gn gen fails with \"Unresolved dependencies\" before anything compiles"
  fi
done

if [ "$FAILED" -gt 0 ]; then
  echo "$FAILED failed"
  exit 1
fi
echo "all ok"
