#!/usr/bin/env bash
# Point the flake's `engine` package at the engine CI published most recently.
#
#   ./scripts/update-engine-release.sh
#
# Regenerates `packages/domicile-engine/engine-release.nix` so each flake
# revision pins one engine build by url and hash.
#
# In CI this runs in the pull request that changes the engine, and pushes the
# result back to that branch. The hash is only known after a build, because
# Chromium builds are not reproducible.
#
# The file also records the series identity, which
# `scripts/test-the-pinned-engine-is-this-series.sh` checks against the
# checkout.
#
# The pinned url is the immutable release named in the nightly's body, not the
# nightly itself: the nightly is recreated on every release, so a url under it
# stops resolving.
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="${DOMICILE_ENGINE_REPO:-cprussin/domicile}"
TAG="${DOMICILE_ENGINE_TAG:-engine-nightly}"
# Set to `engine-official.nix` for the production build, which
# engine-release.yml pins. engine-pin.nix picks which pin is used.
OUT="${DOMICILE_ENGINE_PIN_FILE:-$ROOT/packages/domicile-engine/engine-release.nix}"

for tool in curl jq nix; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "update-engine-release: no $tool on PATH. Run this in \`nix develop\`." >&2
    exit 1
  }
done

auth=()
[ -z "${GH_TOKEN:-}" ] || auth=(-H "Authorization: Bearer $GH_TOKEN")

api="https://api.github.com/repos/$REPO/releases/tags/$TAG"
release="$(curl -fsSL "${auth[@]}" -H "Accept: application/vnd.github+json" "$api")" || {
  echo "update-engine-release: no release tagged $TAG in $REPO." >&2
  exit 1
}

# Follow the immutable release the publisher names in the body, rather than
# guessing its tag. Pushed `engine-v*` tags have none and are already immutable.
immutable="$(printf '%s' "$release" |
  jq -r '.body // ""' |
  sed -n 's/.*immutable release: `\([^`]*\)`.*/\1/p' | head -1)"
if [ -n "$immutable" ] && [ "$immutable" != "$TAG" ]; then
  echo "update-engine-release: $TAG names $immutable, which does not move" >&2
  pinned="$(curl -fsSL "${auth[@]}" -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$REPO/releases/tags/$immutable")" || {
    echo "update-engine-release: $TAG names a release $immutable that is not there." >&2
    exit 1
  }
  release="$pinned"
fi

# Match by suffix because the asset name contains the commit. `endswith` skips
# the `.sha256` file published beside it.
url="$(printf '%s' "$release" |
  jq -r 'first(.assets[] | select((.name? // "") | endswith(".tar.zst"))
         | .browser_download_url) // ""')"
[ -n "$url" ] || {
  echo "update-engine-release: $TAG has no .tar.zst asset. Its assets are:" >&2
  printf '%s' "$release" | jq -r '.assets[]?.name // "(none)"' | sed 's/^/  /' >&2
  exit 1
}

# Read the full series identity from the body. The tag holds only a 12-char
# prefix, and the series check compares the whole value.
identity="$(printf '%s' "$release" |
  jq -r '.body // ""' |
  sed -n 's/.*series identity: `\([0-9a-f]\{64\}\)`.*/\1/p' | head -1)"
[ -n "$identity" ] || {
  echo "update-engine-release: that release does not say which series it was built from." >&2
  echo "Releases published before this existed do not carry it; cut a new one." >&2
  exit 1
}

commit="$(printf '%s' "$release" | jq -r '.target_commitish // ""')"
# A rolling tag's `target_commitish` can be a branch name, so fall back to the
# commit stated in the body.
case "$commit" in
  ([0-9a-f]*[0-9a-f]) ;;
  (*) commit="$(printf '%s' "$release" |
        jq -r '.body // ""' |
        sed -n 's/.*domicile commit: `\([0-9a-f]\{7,40\}\)`.*/\1/p' | head -1)" ;;
esac
[ -n "$commit" ] || {
  echo "update-engine-release: $TAG does not say which commit it was built from." >&2
  exit 1
}

echo "update-engine-release: hashing $url" >&2
hash="$(nix store prefetch-file --json "$url" | jq -r '.hash // ""')" || exit 1
[ -n "$hash" ] || {
  echo "update-engine-release: nix did not report a hash for that asset." >&2
  exit 1
}

cat > "$OUT" <<EOF
# One published engine \`nix build .#engine\` can fetch; engine-pin.nix says
# which of the two pins it does.
#
# GENERATED by scripts/update-engine-release.sh. Edit that, not this.
#
# A fixed-output derivation needs a hash, and a hash pins a build — which is
# the point rather than a cost. Without this file the same flake revision would
# fetch a different engine on different days, and a bug reported against one
# could not be reproduced. With it, a flake revision names exactly one engine,
# and moving to a new one is a commit somebody can look at.
#
# The url is the release tagged with the engine's own SERIES, not
# \`engine-nightly\`: the nightly is deleted and recreated on every release
# run, and a pin to it stops resolving as soon as the next build lands.
#
# \`identity\` is that series — the pin, \`patches/\` and \`src/\` hashed by
# content, the same value \`engine-series-stamp.sh\` uses to decide whether the
# shared checkout needs rebuilding. It is here so that
# \`scripts/test-the-pinned-engine-is-this-series.sh\` can ask, without
# downloading anything, whether the engine this repository pins is the engine
# this repository describes. Two commits that do not move the fork have the
# same identity and so need no repin between them.
{
  identity = "$identity";
  commit = "$commit";
  url = "$url";
  hash = "$hash";
}
EOF

echo "update-engine-release: $OUT now points at ${commit:0:7}, series ${identity:0:12}" >&2
