#!/usr/bin/env bash
# Point the flake's `engine` package at the engine CI published most recently.
#
#   ./scripts/update-engine-release.sh
#
# `engine-nightly` is a rolling tag, and a fixed-output derivation needs a
# hash. So which engine a flake revision runs is written down in
# `packages/domicile-engine/engine-release.nix`, and moving to a newer one is
# a commit rather than a silent change of behavior under an unchanged
# revision. This regenerates that file; the diff is the review.
#
# IN CI THIS RUNS INSIDE THE PULL REQUEST THAT MOVED THE FORK, and the commit
# it produces is pushed back onto that branch — which is what makes an engine
# change one pull request rather than two. `engine.yml` publishes the engine
# from the branch head under a tag naming the SERIES rather than the commit,
# so the url is knowable before anything is merged; the hash is not, because
# Chromium does not build byte-for-byte twice, and that is the whole reason
# this step has to come after a build rather than before one.
#
# THE SERIES IDENTITY IS WRITTEN DOWN TOO, and it is what
# `scripts/test-the-pinned-engine-is-this-series.sh` compares against the fork
# in the checkout. Without it, "this repository describes one engine and ships
# another" is a question nothing can answer locally — which is the state that
# produced #411 and every silent skipped release after it.
#
# WHAT IS PINNED IS NOT THE NIGHTLY. The nightly is deleted and recreated on
# every release run, so a url under that tag stops resolving the moment the
# next build is published -- `nix run` on main answers `cannot download ...
# from any mirror` and every open pull request goes red for a reason none of
# them caused. The publisher puts the same build under a second tag naming its
# commit and never deletes that one, and says which in the nightly's body. So
# the nightly is read to find the newest build, and what gets written down is
# the immutable release's url.
#
# `nix store prefetch-file` does the download and the hash in the format the
# derivation wants, so nothing here computes a digest of its own.
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="${DOMICILE_ENGINE_REPO:-cprussin/domicile}"
TAG="${DOMICILE_ENGINE_TAG:-engine-nightly}"
OUT="$ROOT/packages/domicile-engine/engine-release.nix"

for tool in curl jq nix; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "update-engine-release: no $tool on PATH. Run this in \`nix develop\`." >&2
    exit 1
  }
done

auth=()
[ -z "${GH_TOKEN:-}" ] || auth=(-H "Authorization: Bearer $GH_TOKEN")

api="https://api.github.com/repos/$REPO/releases/tags/$TAG"
release="$(curl -fsSL "${auth[@]}" -H "Accept: application/vnd.github+json" "$api")" || {
  echo "update-engine-release: no release tagged $TAG in $REPO." >&2
  exit 1
}

# The release that keeps existing, named in the body by the publisher rather
# than guessed from the commit -- the tag and the tarball are generated by two
# different scripts, and a third guess here is a third thing to keep in step.
# Absent for a release published before this existed, and for a pushed
# `engine-v*` tag, which is already immutable; both are pinnable as they are.
immutable="$(printf '%s' "$release" |
  jq -r '.body // ""' |
  sed -n 's/.*immutable release: `\([^`]*\)`.*/\1/p' | head -1)"
if [ -n "$immutable" ] && [ "$immutable" != "$TAG" ]; then
  echo "update-engine-release: $TAG names $immutable, which does not move" >&2
  pinned="$(curl -fsSL "${auth[@]}" -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$REPO/releases/tags/$immutable")" || {
    echo "update-engine-release: $TAG names a release $immutable that is not there." >&2
    exit 1
  }
  release="$pinned"
fi

# By suffix, not by name: the name carries the commit, and a lookup that had to
# guess it would have to already know what it was about to fetch. The `.sha256`
# published beside it ends in something else, which is why this is `endswith`
# and not a match anywhere in the name.
url="$(printf '%s' "$release" |
  jq -r 'first(.assets[] | select((.name? // "") | endswith(".tar.zst"))
         | .browser_download_url) // ""')"
[ -n "$url" ] || {
  echo "update-engine-release: $TAG has no .tar.zst asset. Its assets are:" >&2
  printf '%s' "$release" | jq -r '.assets[]?.name // "(none)"' | sed 's/^/  /' >&2
  exit 1
}

# WHICH SERIES THE PUBLISHED BUILD IS OF, out of the body, where the publisher
# states it. Not derived from the tag: the tag carries twelve characters of it
# and the check that reads this file compares the whole thing, so deriving it
# would answer a weaker question than the one asked.
identity="$(printf '%s' "$release" |
  jq -r '.body // ""' |
  sed -n 's/.*series identity: `\([0-9a-f]\{64\}\)`.*/\1/p' | head -1)"
[ -n "$identity" ] || {
  echo "update-engine-release: that release does not say which series it was built from." >&2
  echo "Releases published before this existed do not carry it; cut a new one." >&2
  exit 1
}

commit="$(printf '%s' "$release" | jq -r '.target_commitish // ""')"
# A rolling tag's `target_commitish` can be a branch name rather than a sha, so
# the body — which the publish step writes — is where the commit is stated.
case "$commit" in
  ([0-9a-f]*[0-9a-f]) ;;
  (*) commit="$(printf '%s' "$release" |
        jq -r '.body // ""' |
        sed -n 's/.*domicile commit: `\([0-9a-f]\{7,40\}\)`.*/\1/p' | head -1)" ;;
esac
[ -n "$commit" ] || {
  echo "update-engine-release: $TAG does not say which commit it was built from." >&2
  exit 1
}

echo "update-engine-release: hashing $url" >&2
hash="$(nix store prefetch-file --json "$url" | jq -r '.hash // ""')" || exit 1
[ -n "$hash" ] || {
  echo "update-engine-release: nix did not report a hash for that asset." >&2
  exit 1
}

cat > "$OUT" <<EOF
# Which published engine \`nix build .#engine\` produces.
#
# GENERATED by scripts/update-engine-release.sh. Edit that, not this.
#
# A fixed-output derivation needs a hash, and a hash pins a build — which is
# the point rather than a cost. Without this file the same flake revision would
# fetch a different engine on different days, and a bug reported against one
# could not be reproduced. With it, a flake revision names exactly one engine,
# and moving to a new one is a commit somebody can look at.
#
# The url is the release tagged with the engine's own SERIES, not
# \`engine-nightly\`: the nightly is deleted and recreated on every release
# run, and a pin to it stops resolving as soon as the next build lands.
#
# \`identity\` is that series — the pin, \`patches/\` and \`src/\` hashed by
# content, the same value \`engine-series-stamp.sh\` uses to decide whether the
# shared checkout needs rebuilding. It is here so that
# \`scripts/test-the-pinned-engine-is-this-series.sh\` can ask, without
# downloading anything, whether the engine this repository pins is the engine
# this repository describes. Two commits that do not move the fork have the
# same identity and so need no repin between them.
{
  identity = "$identity";
  commit = "$commit";
  url = "$url";
  hash = "$hash";
}
EOF

echo "update-engine-release: $OUT now points at ${commit:0:7}, series ${identity:0:12}" >&2
