#!/usr/bin/env bash
# Point the flake's `engine` package at the engine CI published most recently.
#
#   ./scripts/update-engine-release.sh
#
# `engine-nightly` is a rolling tag, and a fixed-output derivation needs a
# hash. So which engine a flake revision runs is written down in
# `packages/domicile-engine/engine-release.nix`, and moving to a newer one is
# a commit rather than a silent change of behaviour under an unchanged
# revision. This regenerates that file; the diff is the review.
#
# `nix store prefetch-file` does the download and the hash in the format the
# derivation wants, so nothing here computes a digest of its own.
set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="${DOMICILE_ENGINE_REPO:-cprussin/domicile}"
TAG="${DOMICILE_ENGINE_TAG:-engine-nightly}"
OUT="$ROOT/packages/domicile-engine/engine-release.nix"

for tool in curl jq nix; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "update-engine-release: no $tool on PATH. Run this in \`nix develop\`." >&2
    exit 1
  }
done

auth=()
[ -z "${GH_TOKEN:-}" ] || auth=(-H "Authorization: Bearer $GH_TOKEN")

api="https://api.github.com/repos/$REPO/releases/tags/$TAG"
release="$(curl -fsSL "${auth[@]}" -H "Accept: application/vnd.github+json" "$api")" || {
  echo "update-engine-release: no release tagged $TAG in $REPO." >&2
  exit 1
}

# By suffix, not by name: the name carries the commit, and a lookup that had to
# guess it would have to already know what it was about to fetch. The `.sha256`
# published beside it ends in something else, which is why this is `endswith`
# and not a match anywhere in the name.
url="$(printf '%s' "$release" |
  jq -r 'first(.assets[] | select((.name? // "") | endswith(".tar.zst"))
         | .browser_download_url) // ""')"
[ -n "$url" ] || {
  echo "update-engine-release: $TAG has no .tar.zst asset. Its assets are:" >&2
  printf '%s' "$release" | jq -r '.assets[]?.name // "(none)"' | sed 's/^/  /' >&2
  exit 1
}

commit="$(printf '%s' "$release" | jq -r '.target_commitish // ""')"
# A rolling tag's `target_commitish` can be a branch name rather than a sha, so
# the body — which the publish step writes — is where the commit is stated.
case "$commit" in
  ([0-9a-f]*[0-9a-f]) ;;
  (*) commit="$(printf '%s' "$release" |
        jq -r '.body // ""' |
        sed -n 's/.*domicile commit: `\([0-9a-f]\{7,40\}\)`.*/\1/p' | head -1)" ;;
esac
[ -n "$commit" ] || {
  echo "update-engine-release: $TAG does not say which commit it was built from." >&2
  exit 1
}

echo "update-engine-release: hashing $url" >&2
hash="$(nix store prefetch-file --json "$url" | jq -r '.hash // ""')" || exit 1
[ -n "$hash" ] || {
  echo "update-engine-release: nix did not report a hash for that asset." >&2
  exit 1
}

cat > "$OUT" <<EOF
# Which published engine \`nix run .#engine\` runs.
#
# GENERATED by scripts/update-engine-release.sh. Edit that, not this.
#
# A fixed-output derivation needs a hash, and a hash pins a build — which is
# the point rather than a cost. \`engine-nightly\` is a rolling tag: without
# this file the same flake revision would fetch a different engine on different
# days, and a bug reported against one could not be reproduced. With it, a
# flake revision names exactly one engine, and moving to a new one is a commit
# somebody can look at.
{
  commit = "$commit";
  url = "$url";
  hash = "$hash";
}
EOF

echo "update-engine-release: $OUT now points at ${commit:0:7}" >&2
